const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    //customer
    ADD_CUSTOMER_SUCCESS: 'ADD_CUSTOMER_SUCCESS',
    CUSTOMER_LOGIN_SUCCESS: 'CUSTOMER_LOGIN_SUCCESS',
    CUSTOMER_LOGIN_FAIL: 'CUSTOMER_LOGIN_FAIL',
    PROCESS_CUSTOMER_LOGOUT: 'PROCESS_CUSTOMER_LOGOUT',

    //staff
    ADD_STAFF_SUCCESS: 'ADD_STAFF_SUCCESS',
    STAFF_LOGIN_SUCCESS: 'STAFF_LOGIN_SUCCESS',
    STAFF_LOGIN_FAIL: 'STAFF_LOGIN_FAIL',
    PROCESS_STAFF_LOGOUT: 'PROCESS_STAFF_LOGOUT',
})

export default actionTypes;